spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network  # (data base name)
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # or even create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql  # help the also jpa and hibernate to better prepare query
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# this configuration is also valid for different provider
  mail:
    host: localhost
    port: 1025     # the port that we declare in docker-compose.yml in nail-dev port part
    username: ali  # you can type anything
    password: ali  # you can type anything
    properties:
      mail:
        smtp:
          trust: "*"  # here we sat what we want to trust ,not recommend for production
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000   # after 5 seconds the connection timeout
        timeout: 3000
        writetimeout: 5000


#application:
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days
#  mailing:
#    frontend:
#      activation-url: http://localhost:4200/activate-account
#  file:
#    uploads:
#      photos-output-path: ./uploads
#
#
#server:
#  port: 8088